### ISSUE TITLE
PaymentEngines uninitialized

### ISSUE THREAD

**Issue by clauda** [devton/catarse_paypal_express#1]
what's wrong?

```
(...) /gems/catarse_paypal_express-40480eb292de/config/initializers/
register.rb:1:in `<top (required)>': 
uninitialized constant PaymentEngines (NameError)
```

**Comment by diogob** [comment]
Sorry, If you make a pull now it should work. The payment engines are using a new interface in Catarse main code to register them. From now on this coupling should be less of a concern :)

**Comment by clauda** [comment]
I get it, this interface in Catarse project was added a day ago, right?
thanks @diogob

**Comment by diogob** [comment]
Yes, that's it

**Comment by manwithtwowatches** [comment]
hey man, could you help me out? i cloned and have been modifying catarse for a while now and just came across this problem today. i've been looking through the latest cut of the code but can't see what i need to change in order to get this line working. i can't merge in the changes so need to do it manually i think. can you give me some pointers please? i can't see anything in the code to do with PaymentEngines. any help is much appreciated, thanks!

**Comment by diogob** [comment]
take a look at: lib/payment_engines.rb
Just a word of advice, the code in our master branch is moving very fast and we are refactoring tons of stuff, I strongly recommend that you try to get back to a state where you could automatically merge.

**Comment by manwithtwowatches** [comment]
ah yes, looking at old code. it actually hadn't even occurred to me that catarse was still being developed. thanks for the headsup!

**Comment by mikepence** [comment]
Seems to still be an issue.

**Comment by phlegx** [comment]
:+1:
